## docker-compose.yml

version: "3.8"
services:
    dnsdist:
        ## Never deploy more than 1 dnsdist instance per host.
        container_name: dnsdist
        networks:
            dns:
                ipv4_address: 172.16.53.10
        image: docker.io/rootwyrm/dnsdist:latest
        ports:
            - "172.16.53.1:53:53"
            - "80:80/tcp"
            - "443:443/tcp"
            - "8053:8053/tcp"
        sysctls:
            - net.core.somaxconn=10240
            #- net.core.rmem_max=12582912
            #- net.core.wmem_max=12582912
            - net.ipv4.tcp_rmem=10240 87380 12582912
            - net.ipv4.tcp_wmem=10240 87380 12582912
            - net.ipv4.tcp_fin_timeout=15
            - net.ipv4.tcp_tw_reuse=1
            - net.ipv4.tcp_fastopen=3
        restart: on-failure
        tmpfs:
            - /run
            - /tmp
        volumes:
            - "/opt/rootwyrm/etc/dnsdist:/usr/local/etc/dnsdist"
        cap_add:
            - NET_ADMIN
            - NET_BIND_SERVICE

networks:
    dns:
        ipam:
            #driver: "bridge"
            config:
                - subnet: "172.16.53.0/24"

