#!/bin/bash
################################################################################
## sv/nsd/control/d
################################################################################

nsdconf="/usr/local/etc/nsd/nsd.conf"

nsd_stop() {
	echo -n "Writing out nsd zonefiles..."
	/usr/local/sbin/nsd-control write
	
	echo -n "Stopping nsd..."
	/usr/local/sbin/nsd-control stop
}

nsd_stop
