#!/bin/bash
################################################################################
## sv/nsd/control/h
################################################################################

nsdconf="/usr/local/etc/nsd/nsd.conf"

nsd_hup() {
	echo -n "Writing out nsd zonefiles..."
	/usr/local/sbin/nsd-control write
	
	echo "Reloading nsd..."
	/usr/local/sbin/nsd-control reconfig
}

nsd_hup
