#!/bin/bash
################################################################################
## sv/nsd/control/t
################################################################################

nsdconf="/usr/local/etc/nsd/nsd.conf"

nsd_term() {
	echo -n "Writing out nsd zonefiles..."
	/usr/local/sbin/nsd-control write
	
	echo -n "Terminating nsd..."
	/usr/local/sbin/nsd-control stop
}

nsd_term
