#!/bin/bash
## nsd

nsdconf="/usr/local/etc/nsd/nsd.conf"

if [ -f /firstboot ]; then
	echo "[nsd] Waiting for firstboot scripts..."
	sleep 60
fi

nsd_config_test()
{
	if [ ! -f $nsdconf ]; then
		printf '[nsd] No configuration present at %s!\n' "$nsdconf"
		exit 1
	fi
	printf '[nsd] Testing configuration...'
	if [ $? -ne 0 ]; then
		RC=$?
		printf 'ERROR %s\n' "$RC"
		exit $RC
	else
		printf 'OK\n'
	fi
}

nsd_start() {
	## Guarantee clean shutdown when we're running
	if [ ! -f /etc/runit/stopit ]; then
		touch /etc/runit/stopit
		chmod u+x /etc/runit/stopit
	else
		chmod u+x /etc/runit/stopit
	fi

	# Trap signals
	#trap "nsd_stop; exit" 1 3 9 15 17 18 19

	nsd_config_test

	printf '[nsd] Starting nsd...\n'
	exec /usr/local/sbin/nsd -d -c $nsdconf -P /var/db/nsd/nsd.pid -u nsd -l /var/log/nsd.log
}	

nsd_start
