#!/bin/sh
## dnsdist

dduser=dnsdist
ddgroup=dnsdist

echo "Starting dnsdist as $dduser:$ddgroup"
echo " "

exec /usr/local/bin/dnsdist -C /usr/local/etc/dnsdist/dnsdist.conf -u $dduser -g $dduser --supervised
