#!/bin/sh
## nsd

nsdconf="/usr/local/etc/nsd/nsd.conf"

if [ -f /firstboot ]; then
	echo "[nsd] Waiting for firstboot scripts..."
	sleep 60
fi

if [ ! -f $nsdconf ]; then
	echo "[nsd] No configuration present!"
	exit 1
else
	echo "[nsd] Testing configuration..."
	/usr/local/sbin/nsd-checkconf ${nsdconf}
	if [ $? -ne 0 ]; then
		RC=$?
		echo "[nsd] Configuration test failed - $RC"
		exit $RC
	fi
fi

echo "[nsd] Starting nsd..."
echo " "
exec /usr/local/sbin/nsd -c $nsdconf -d -u nsd -P /var/db/nsd/nsd.pid -l /dev/stdout
