## base
name: Build - base
on:
  push:
    branches: [ master ]
    paths:
      - 'base/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'base/*'

## Rebuild
jobs:
  base:
    name: Image - base
    runs-on: ubuntu-20.04
    env:
      CONTAINER: base
      PLATFORM: "linux/amd64,linux/386,linux/arm64,linux/arm/v7"
      BINFMT: a7996909642ee92942dcd6cff44b9b95f08dad64
    steps:
    - name: Check out from HEAD
      uses: actions/checkout@v2
    - name: Run pre_build hooks
      run: |
        $GITHUB_WORKSPACE/ci/hooks/pre_build
    - name: Set up architectures
      run: |
        docker run --rm --privileged docker/binfmt:$BINFMT 
        docker buildx create --name $CONTAINER 
        docker buildx use $CONTAINER
    - name: Build for all platforms
      run: |
        docker login -u ${{ secrets.HUB_USER }} -p ${{ secrets.HUB_TOKEN }}
        docker buildx build --platform $PLATFORM \
        --pull --push \
        --tag rootwyrm/dns_$CONTAINER $CONTAINER 
  consumers:
    needs: base
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        consumers: [ nsd ]
    env:
      RW_PROJECT: dns_docker
    steps:
    - name: Trigger consumers
      run: |
        curl -u ${{ github.actor }}:${{ secrets.FLOW_TOKEN }} \
          https://api.github.com/repos/rootwyrm/$RW_PROJECT/dispatches \
          -H 'User-Agent: rootwyrm/dnsdocker/.github/workflows' \
          --data '{ "event_type": "${{ matrix.consumers }}", "client_payload": { "build": "true" } }'

# vim:ts=2:sw=2:et
