## cicd.yml
name: CI - Validate Builds
on:
  push:
    paths:
      - 'ci/hooks/**'
      - 'container/**'
    repository_dispatch:
      types: [ run_ci ]
    workflow_dispatch:

## Build x86 and aarch64 separately to speed it up
jobs:
  ######################################################################
  ## x86_64
  ######################################################################
  x86_64:
    name: CI Build - x86_64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ base, nsd, unbound, bind ]
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Run pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build $GITHUB_WORKSPACE/container/${{ matrix.container }}/Dockerfile
      - name: CI - Build ${{ matrix.container }}
        id: build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${{ matrix.container }}
          pull: true
          push: false
          tags: rootwyrm/dns_${{ matrix.container }}:cibuild
  arm64:
    name: CI Build - arm64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ base, nsd, unbound, bind ]
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Run pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build $GITHUB_WORKSPACE/container/${{ matrix.container }}/Dockerfile
      - name: CI - Build ${{ matrix.container }}
        id: build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${{ matrix.container }}
          pull: true
          push: false
          tags: rootwyrm/dns_${{ matrix.container }}:cibuild
