################################################################################
# Builds and pushes base to latest, does NOT push child images.
# ONLY checks child builds.
################################################################################
name: CI - World
on:
  push:
    branches: [ master ]
    paths: 
      - 'ci/**'
      - 'base/**'
      - 'dnsdist/**'
      - 'nsd/**'
      - 'unbound/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'ci/**'
      - 'base/**'
      - 'dnsdist/**'
      - 'nsd/**'
      - 'unbound/**'
  pull_request_review:
    types: [ submitted, edited ]
  repository_dispatch:
    types: [ ci_quick ]

jobs:
################################################################################
# Base Container
################################################################################
  validate_base:
    name: Validate base image
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout from ${{ github.ref }} triggered by ${{ github.actor }}
      uses: actions/checkout@v2
      id: checkout
    - name: Validate base container integrity
      id: validate
      run: |
        docker build base --file base/Dockerfile \
        --no-cache --label=base_validate --rm \
        --tag dns_base:$(date +%s)
  base:
    name: Build base container
    needs: validate_base
    runs-on: ubuntu-20.04
    env:
      BINFMT: a7996909642ee92942dcd6cff44b9b95f08dad64
      CONTAINER: base
      PLATFORM: "linux/amd64,linux/386,linux/arm64,linux/arm/v7"
      RW_TAG: rootwyrm/dns_base
    steps:
    - name: Check out from ${{ github.ref }}
      id: checkout
      uses: actions/checkout@v2
    - name: Run pre-build hooks
      id: hooks
      run: |
        $GITHUB_WORKSPACE/ci/hooks/pre_build
    - name: Set up build environment
      id: buildenv
      run: |
        docker run --rm --privileged docker/binfmt:$BINFMT
        docker buildx create --name rootwyrm --use
    - name: Build for platforms
      run: |
        docker login -u ${{ secrets.HUB_USER }} -p ${{ secrets.HUB_TOKEN }}
        docker buildx build --platform $PLATFORM --pull --push \
        --tag $RW_TAG:latest \
        $CONTAINER 

################################################################################
# Consumers
################################################################################
  consumers:
    needs: base
    strategy:
      matrix:
        consumer: [ dnsdist, nsd, unbound ]
    name: CI - Consumer ${{ matrix.consumer }}
    runs-on: ubuntu-20.04
    steps:
    - name: Check out from ${{ github.ref }}
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run pre-build hooks
      run: |
        ${GITHUB_WORKSPACE}/ci/hooks/pre_build
    - name: Build ${{ matrix.consumer }}
      run: |
        docker build ${{ matrix.consumer }} --pull \
        --file ${{ matrix.consumer }}/Dockerfile \
        --no-cache --label=${{ matrix.consumer }} --rm \
        --tag ${{ matrix.consumer }}:$(date +%s)

# vim:ts=2:sw=2:et
