## dnsdist
name: Build - dnsdist
on:
  push:
    branches: [ master ]
    paths:
      - 'dnsdist/**/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'dnsdist/**/*'

## Rebuild
jobs:
  dnsdist:
    strategy:
      matrix:
        platform: [ linux/amd64, linux/386, linux/arm64, linux/arm/v7 ]
    name: dnsdist - ${{ matrix.platform }}
    runs-on: ubuntu-20.04
    env:
      CONTAINER: dnsdist
      BINFMT: a7996909642ee92942dcd6cff44b9b95f08dad64
    steps:
    - name: Check out from ${{ github.ref }} triggered by ${{ github.actor }}
      id: checkout
      uses: actions/checkout@v2
    - name: Run pre-build hooks
      id: hooks
      run: |
        $GITHUB_WORKSPACE/ci/hooks/pre_build
    - name: Set up build environment
      id: buildenv
      run: |
        docker run --rm --privileged docker/binfmt:$BINFMT
        docker buildx create --name rootwyrm --use
    - name: Build for ${{ matrix.platform }}
      run: |
        PLATFORM_TAG=$(echo ${{ matrix.platform }} | sed -e 's,linux/,,' | sed -e 's,/,,g')
        docker login -u ${{ secrets.HUB_USER }} -p ${{ secrets.HUB_TOKEN }}
        docker buildx build --platform ${{ matrix.platform }} \
        --tag rootwyrm/$CONTAINER:$PLATFORM_TAG \
        --pull --push $CONTAINER
  dnsdist_package:
    needs: dnsdist
    name: Package and ship dnsdist
    runs-on: ubuntu-20.04
    steps:
      - name: Check out from ${{ github.ref }}
        uses: actions/checkout@v2
      - name: Ship dnsdist manifest
        run: |
          docker login -u ${{ secrets.HUB_USER }} -p ${{ secrets.HUB_TOKEN }}
          ${GITHUB_WORKSPACE}/ci/tools/manifest.sh dnsdist

# vim:ts=2:sw=2:et
