name: dns_docker dnsdist Image
on:
  push:
    branches: [ master ]
    paths: 'dnsdist/*'
  pull_request:
    branches: [ master ]
    paths: 'dnsdist/*'
jobs:
  dnsdist:
    runs-on: ubuntu-latest
    env:
      CONTAINER: dnsdist
    steps:
    - name: Check out from HEAD
      uses: actions/checkout@v2
    - shell: bash
      run: |
        $GITHUB_WORKSPACE/ci/hooks/pre_build
    - name: Build from HEAD and push as latest
      uses: docker/build-push-action@v1.1.0
      with:
        always_pull: true
        add_git_labels: true
        tag_with_ref: true
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}
        repository: rootwyrm/dnsdist
        path: dnsdist

# vim:ft=yaml:sw=2:ts=2:et
