## Base Image
name: Base Image
on:
  push:
    branches: [ master ]
    paths: 'base/*'
  pull_request:
    branches: [ master ]
    paths: 'base/*'
jobs:
  ## Validate on GitHub, which is faster.
  base_validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Perform CI test on GitHub
      run: docker build base --file base/Dockerfile --tag dns_docker:$(date +%s)
  base_image_build:
    needs: base_validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out from HEAD
        uses: actions/checkout@v2
      ## Establish fixed point in time.
      - shell: bash
        run: |
          date '+%FT%T.%N%:z' > timestamp ; export RW_BUILDDATE=$(cat timestamp)
      - shell: bash
        run: |
          echo "RW_BUILDDATE $RW_BUILDDATE"
          echo "GITHUB_WORKFLOW $GITHUB_WORKFLOW"
          echo "GITHUB_REF $GITHUB_REF"
      - name: Build from HEAD and push as latest
        uses: docker/build-push-action@v1.1.0
        with:
          always_pull: true
          add_git_labels: true
          tag_with_ref: true
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_TOKEN }}
          repository: rootwyrm/dns_base
          path: base
          dockerfile: base/Dockerfile.test
          labels: com.rootwyrm.docker.auto=$GITHUB_WORKFLOW,com.rootwyrm.dns_docker.version=$GITHUB_REF,org.label-schema.vcs-ref=$GITHUB_SHA,org.label-schema.version=$GITHUB_SHA,org.label-schema.build-date=$RW_BUILDDATE

# vim:ft=yaml:sw=2:ts=2:et
