## Base Image
name: Base Image
on:
  push:
    branches: [ master ]
    paths: 'base/*'
  pull_request:
    branches: [ master ]
    paths: 'base/*'
jobs:
  ## Validate on GitHub, which is faster.
  base_validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Perform CI test on GitHub
      run: docker build base --file base/Dockerfile --tag dns_docker:$(date +%s)
  amd64:
    needs: base_validate
    runs-on: ubuntu-latest
    env:
      CONTAINER: base
    steps:
      - name: Check out from HEAD
        uses: actions/checkout@v2
      ## Establish fixed point in time.
      - shell: bash
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Build from HEAD and push as latest
        uses: docker/build-push-action@v1.1.0
        with:
          always_pull: true
          add_git_labels: true
          tag_with_ref: true
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_TOKEN }}
          repository: rootwyrm/dns_base
          path: base
      - name: Check for docker buildx
        run: |
          docker buildx
          echo ::set-output name=docker_buildx::$(docker buildx)
      - name: Show if it's there
        run: |
          echo "docker buildx result ${{ steps.amd64.docker_buildx }}"
  aarch64:
    needs: base_validate
    runs-on: ubuntu-latest
    env:
      CONTAINER: base
    steps:
      - name: Check out from HEAD
        uses: actions/checkout@v2
      - name: aarch64 step 1 test
        uses: uramio/run-on-arch-action@master
        id: aarch64_test
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            apt update
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output from test
        run: |
          echo "uname output was ${{ steps.aarch64_test.uname }}"

# vim:ft=yaml:sw=2:ts=2:et
