## Testing if we can do a tiered tree
name: Tree testing
on:
  push:
    branches: [ master ] 

jobs:
  nsd_build_amd64:
    name: nsd - build amd64
    runs-on: ubuntu-20.04
    env:
      CONTAINER: nsd
      ARCH_BUILD: amd64
      BINFMT: a7996909642ee92942dcd6cff44b9b95f08dad64
    steps:
      - name: Check out from HEAD
        uses: actions/checkout@v2
      - name: Run pre_build hooks
        shell: bash
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Set up architectures
        shell: bash
        run: |
          docker run --rm --privileged docker/binfmt:$BINFMT
          docker buildx create --name $CONTAINER
          docker buildx use $CONTAINER
      - name: Build linux/${{ ARCH_BUILD }}
        shell: bash
        run: |
          docker buildx build --platform linux/$ARCH_BUILD --tag rootwyrm/$CONTAINER $CONTAINER --pull
  nsd_build_386:
    name: nsd - build 386
    runs-on: ubuntu-20.04
    env:
      CONTAINER: nsd
      ARCH_BUILD: 386
      BINFMT: a7996909642ee92942dcd6cff44b9b95f08dad64
    steps:
      - name: Check out from HEAD
        uses: actions/checkout@v2
      - name: Run pre_build hooks
        shell: bash
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Set up architectures
        shell: bash
        run: |
          docker run --rm --privileged docker/binfmt:$BINFMT
          docker buildx create --name $CONTAINER
          docker buildx use $CONTAINER
      - name: Build linux/${{ ARCH_BUILD }}
        shell: bash
        run: |
          docker buildx build --platform linux/$ARCH_BUILD --tag rootwyrm/$CONTAINER $CONTAINER --pull

# vim:ts=2:sw=2:et
