## Testing if we can do a tiered tree
name: Tree testing
on:
  push:
    branches: [ master ] 

jobs:
  nsd_test:
    name: nsd Tree Test
    runs-on: ubuntu-20.04
    env:
      CONTAINER: nsd
      BINFMT: a7996909642ee92942dcd6cff44b9b95f08dad64
    steps:
      - name: Check out from HEAD
        uses: actions/checkout@v2
      - name: Run pre_build hooks
        shell: bash
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Set up architectures
        shell: bash
        run: |
          docker run --rm --privileged docker/binfmt:$BINFMT
          docker buildx create --name $CONTAINER
          docker buildx use $CONTAINER
      - name: Execute platform builds
        - name: amd64
          shell: bash
          run: |
            docker buildx build --platform linux/amd64 --tag rootwyrm/$CONTAINER $CONTAINER --pull
        - name: 386
          shell: bash
            docker buildx build --platform linux/386 --tag rootwyrm/$CONTAINER $CONTAINER --pull

# vim:ts=2:sw=2:et
